# Generated by Django 4.0.2 on 2022-03-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='paswword',
            new_name='password',
        ),
    ]
